const CONFIG = {
  github: {
    username: "namitaggarwal",
  },
  base: "/",
  projects: {
    github: {
      display: true,
      header: 'Github Projects',
      mode: 'automatic',
      automatic: {
        sortBy: 'stars',
        limit: 8,
        exclude: {
          forks: false,
          projects: [],
        },
      },
      manual: {
        projects: ['namitaggarwal/phewtube'],
      },
    },
    external: {
      header: 'My Projects',
      projects: [
        {
          title: 'phewtube',
          description:
            'Minimal YouTube-like app: Node.js/Express + Prisma (SQLite) backend with HLS transcoding, and React + Vite frontend.',
          imageUrl:
            'https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg',
          link: 'https://github.com/namitaggarwal/phewtube',
        },
      ],
    },
  },
  seo: { title: 'Portfolio of Namit Aggarwal', description: 'Senior Software Engineer', imageURL: 'https://drive.google.com/file/d/15lRKuSGQuiKPyKQ-jgdsWplYV9KuQWAR/view?usp=sharing' },
  name: "NAMIT AGGARWAL",
  profession: "Senior Software Engineer",
  location: "Delhi, India",
  email: "namitaggarwal.fullstack@gmail.com",
  website: "",

  social: {
    linkedin: "namitfullstack/",
    x: "namitaggarwal12",
    mastodon: "",
    researchGate: "",
    facebook: "",
    instagram: "",
    reddit: "",
    threads: "",
    youtube: "",
    udemy: "",
    dribbble: "",
    behance: "",
    medium: "",
    dev: "",
    stackoverflow: "",
    discord: "",
    telegram: "",
    website: "",
    phone: "",
    email: "namitaggarwal.fullstack@gmail.com",
  },
  resume: {
    fileUrl: "https://drive.google.com/file/d/1krNpvzHLZq4_AdbRg6VR5VHRFXBzjuwj/view?usp=drive_link",
  },
  skills: [
    "JavaScript",
    "TypeScript",
    "Core Java",
    "Selenium",
    "WebdriverIO",
    "Playwright",
    "ShellScript",
    "Groovy",
    "Jenkins",
    "Maven",
    "Git/GitHub",
    "JUnit",
    "TestNG",
    "SonarQube",
    "QTest",
    "PostgreSQL",
    "MySQL",
    "AWS",
    "Azure",
    "Splunk",
    "Cypress (learning)",
    "Machine Learning (beginner)",
  ],
  experiences: [
    {
      company: "Adobe Systems",
      position: "Senior Software Engineer",
      from: "April 2023",
      to: "Present",
      companyLink: "",
      description: "Worked on AEM automation, parallel execution with TestNG, and improving E2E coverage along with Dynamic Media workflows.",
    },
    {
      company: "Hughes Systique Corporation",
      position: "Software Engineer",
      from: "December 2021",
      to: "March 2023",
      companyLink: "",
      description: "Working on Jenkins, Selenium Webdriver, Core Java, and Integration Testing for Hughes Network System(HNS).",
    },
    {
      company: "ACS Infotech Pvt Ltd",
      position: "Software Engineer",
      from: "February 2020",
      to: "November 2021",
      companyLink: "",
      description: "Working on Jenkins, Selenium, Core Java, and End to End Testing for INFOMAN eDMS & Samadhan V2(EM3 Agri Service).",
    },
  ],
  certifications: [
    {
      name: "",
      body: "",
      year: "",
      link: "",
    },
  ],
  educations: [
    {
      institution: "K.R. Mangalam University",
      degree: "Bachelor of Technology in Electronics and Communication Engineering (ECE)",
      from: "2015",
      to: "2019",
    },
  ],
  publications: [],
  blog: {
    source: "dev",
    username: "",
    limit: 2,
  },
  // googleAnalytics: {
  //   id: "",
  // },
  hotjar: { id: "", snippetVersion: 6 },
  themeConfig: {
    defaultTheme: "lofi",
    disableSwitch: false,
    respectPrefersColorScheme: false,
    displayAvatarRing: true,
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
      "caramellatte",
      "abyss",
      "silk",
      "procyon",
    ],
  },
  footer: `Made with <a 
      class="text-primary" href="https://github.com/namitaggarwal/namitaggarwal.github.io"
      target="_blank"
      rel="noreferrer"
    >GitProfile</a> and ❤️`,
  enablePWA: true,
};

export default CONFIG;
